classdef UI < uint8
    %UI User interface events
    %   This enumeration class defines the ui events.    
    %
    % Copyright 2021 The MathWorks, Inc.
    %
    enumeration
        click(0),...
        dblclick(1),...
        contextmenu(2),...
        mousedown(3),...
        mouseup(4),...
        mouseenter(5),...
        mouseleave(6),...
        mousemove(7),...
        mouseout(8),...
        mouseover(9)
    end
        
end
